# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dadosgov',
                'doc_host': 'https://jhenriquetdg.github.io',
                'git_url': 'https://github.com/jhenriquetdg/dadosgov',
                'lib_path': 'dadosgov'},
  'syms': { 'dadosgov.core': { 'dadosgov.core.foo': ('core.html#foo', 'dadosgov/core.py'),
                               'dadosgov.core.test': ('core.html#test', 'dadosgov/core.py')}}}
